<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $value=array(
              array( 'id'=>'1', 'sortname' => 'AF', 'name' =>'Afghanistan'),
              array( 'id'=>'2', 'sortname' => 'AL', 'name' =>'Albania'),
              array( 'id'=>'3', 'sortname' => 'DZ', 'name' =>'Algeria'),
              array( 'id'=>'4', 'sortname' => 'AS', 'name' =>'American Samoa'),
              array( 'id'=>'5', 'sortname' => 'AD', 'name' =>'Andorra'),
              array( 'id'=>'6', 'sortname' => 'AO', 'name' =>'Angola'),
              array( 'id'=>'7', 'sortname' => 'AI', 'name' =>'Anguilla'),
              array( 'id'=>'8', 'sortname' => 'AQ', 'name' =>'Antarctica'),
              array( 'id'=>'9', 'sortname' => 'AG', 'name' =>'Antigua And Barbuda'),
              array( 'id'=>'10', 'sortname' => 'AR', 'name' =>'Argentina'),
              array( 'id'=>'11', 'sortname' => 'AM', 'name' =>'Armenia'),
              array( 'id'=>'12', 'sortname' => 'AW', 'name' =>'Aruba'),
              array( 'id'=>'13', 'sortname' => 'AU', 'name' =>'Australia'),
              array( 'id'=>'14', 'sortname' => 'AT', 'name' =>'Austria'),
              array( 'id'=>'15', 'sortname' => 'AZ', 'name' =>'Azerbaijan'),
              array( 'id'=>'16', 'sortname' => 'BS', 'name' =>'Bahamas The'),
              array( 'id'=>'17', 'sortname' => 'BH', 'name' =>'Bahrain'),
              array( 'id'=>'18', 'sortname' => 'BD', 'name' =>'Bangladesh'),
              array( 'id'=>'19', 'sortname' => 'BB', 'name' =>'Barbados'),
              array( 'id'=>'20', 'sortname' => 'BY', 'name' =>'Belarus'),
              array( 'id'=>'21', 'sortname' => 'BE', 'name' =>'Belgium'),
              array( 'id'=>'22', 'sortname' => 'BZ', 'name' =>'Belize'),
              array( 'id'=>'23', 'sortname' => 'BJ', 'name' =>'Benin'),
              array( 'id'=>'24', 'sortname' => 'BM', 'name' =>'Bermuda'),
              array( 'id'=>'25', 'sortname' => 'BT', 'name' =>'Bhutan'),
              array( 'id'=>'26', 'sortname' => 'BO', 'name' =>'Bolivia'),
              array( 'id'=>'27', 'sortname' => 'BA', 'name' =>'Bosnia and Herzegovina'),
              array( 'id'=>'28', 'sortname' => 'BW', 'name' =>'Botswana'),
              array( 'id'=>'29', 'sortname' => 'BV', 'name' =>'Bouvet Island'),
              array( 'id'=>'30', 'sortname' => 'BR', 'name' =>'Brazil'),
              array( 'id'=>'31', 'sortname' => 'IO', 'name' =>'British Indian Ocean Territory'),
              array( 'id'=>'32', 'sortname' => 'BN', 'name' =>'Brunei'),
              array( 'id'=>'33', 'sortname' => 'BG', 'name' =>'Bulgaria'),
              array( 'id'=>'34', 'sortname' => 'BF', 'name' =>'Burkina Faso'),
              array( 'id'=>'35', 'sortname' => 'BI', 'name' =>'Burundi'),
              array( 'id'=>'36', 'sortname' => 'KH', 'name' =>'Cambodia'),
              array( 'id'=>'37', 'sortname' => 'CM', 'name' =>'Cameroon'),
              array( 'id'=>'38', 'sortname' => 'CA', 'name' =>'Canada'),
              array( 'id'=>'39', 'sortname' => 'CV', 'name' =>'Cape Verde'),
              array( 'id'=>'40', 'sortname' => 'KY', 'name' =>'Cayman Islands'),
              array( 'id'=>'41', 'sortname' => 'CF', 'name' =>'Central African Republic'),
              array( 'id'=>'42', 'sortname' => 'TD', 'name' =>'Chad'),
              array( 'id'=>'43', 'sortname' => 'CL', 'name' =>'Chile'),
              array( 'id'=>'44', 'sortname' => 'CN', 'name' =>'China'),
              array( 'id'=>'45', 'sortname' => 'CX', 'name' =>'Christmas Island'),
              array( 'id'=>'46', 'sortname' => 'CC', 'name' =>'Cocos (Keeling) Islands'),
              array( 'id'=>'47', 'sortname' => 'CO', 'name' =>'Colombia'),
              array( 'id'=>'48', 'sortname' => 'KM', 'name' =>'Comoros'),
              array( 'id'=>'49', 'sortname' => 'CG', 'name' =>'Congo'),
              array( 'id'=>'50', 'sortname' => 'CD', 'name' =>'Congo The Democratic Republic Of The'),
              array( 'id'=>'51', 'sortname' => 'CK', 'name' =>'Cook Islands'),
              array( 'id'=>'52', 'sortname' => 'CR', 'name' =>'Costa Rica'),
              array( 'id'=>'53', 'sortname' => 'CI', 'name' =>"Cote D'Ivoire (Ivory Coast)"),
              array( 'id'=>'54', 'sortname' => 'HR', 'name' =>'Croatia (Hrvatska)'),
              array( 'id'=>'55', 'sortname' => 'CU', 'name' =>'Cuba'),
              array( 'id'=>'56', 'sortname' => 'CY', 'name' =>'Cyprus'),
              array( 'id'=>'57', 'sortname' => 'CZ', 'name' =>'Czech Republic'),
              array( 'id'=>'58', 'sortname' => 'DK', 'name' =>'Denmark'),
              array( 'id'=>'59', 'sortname' => 'DJ', 'name' =>'Djibouti'),
              array( 'id'=>'60', 'sortname' => 'DM', 'name' =>'Dominica'),
              array( 'id'=>'61', 'sortname' => 'DO', 'name' =>'Dominican Republic'),
              array( 'id'=>'62', 'sortname' => 'TP', 'name' =>'East Timor'),
              array( 'id'=>'63', 'sortname' => 'EC', 'name' =>'Ecuador'),
              array( 'id'=>'64', 'sortname' => 'EG', 'name' =>'Egypt'),
              array( 'id'=>'65', 'sortname' => 'SV', 'name' =>'El Salvador'),
              array( 'id'=>'66', 'sortname' => 'GQ', 'name' =>'Equatorial Guinea'),
              array( 'id'=>'67', 'sortname' => 'ER', 'name' =>'Eritrea'),
              array( 'id'=>'68', 'sortname' => 'EE', 'name' =>'Estonia'),
              array( 'id'=>'69', 'sortname' => 'ET', 'name' =>'Ethiopia'),
              array( 'id'=>'70', 'sortname' => 'XA', 'name' =>'External Territories of Australia'),
              array( 'id'=>'71', 'sortname' => 'FK', 'name' =>'Falkland Islands'),
              array( 'id'=>'72', 'sortname' => 'FO', 'name' =>'Faroe Islands'),
              array( 'id'=>'73', 'sortname' => 'FJ', 'name' =>'Fiji Islands'),
              array( 'id'=>'74', 'sortname' => 'FI', 'name' =>'Finland'),
              array( 'id'=>'75', 'sortname' => 'FR', 'name' =>'France'),
              array( 'id'=>'76', 'sortname' => 'GF', 'name' =>'French Guiana'),
              array( 'id'=>'77', 'sortname' => 'PF', 'name' =>'French Polynesia'),
              array( 'id'=>'78', 'sortname' => 'TF', 'name' =>'French Southern Territories'),
              array( 'id'=>'79', 'sortname' => 'GA', 'name' =>'Gabon'),
              array( 'id'=>'80', 'sortname' => 'GM', 'name' =>'Gambia The'),
              array( 'id'=>'81', 'sortname' => 'GE', 'name' =>'Georgia'),
              array( 'id'=>'82', 'sortname' => 'DE', 'name' =>'Germany'),
              array( 'id'=>'83', 'sortname' => 'GH', 'name' =>'Ghana'),
              array( 'id'=>'84', 'sortname' => 'GI', 'name' =>'Gibraltar'),
              array( 'id'=>'85', 'sortname' => 'GR', 'name' =>'Greece'),
              array( 'id'=>'86', 'sortname' => 'GL', 'name' =>'Greenland'),
              array( 'id'=>'87', 'sortname' => 'GD', 'name' =>'Grenada'),
              array( 'id'=>'88', 'sortname' => 'GP', 'name' =>'Guadeloupe'),
              array( 'id'=>'89', 'sortname' => 'GU', 'name' =>'Guam'),
              array( 'id'=>'90', 'sortname' => 'GT', 'name' =>'Guatemala'),
              array( 'id'=>'91', 'sortname' => 'XU', 'name' =>'Guernsey and Alderney'),
              array( 'id'=>'92', 'sortname' => 'GN', 'name' =>'Guinea'),
              array( 'id'=>'93', 'sortname' => 'GW', 'name' =>'Guinea-Bissau'),
              array( 'id'=>'94', 'sortname' => 'GY', 'name' =>'Guyana'),
              array( 'id'=>'95', 'sortname' => 'HT', 'name' =>'Haiti'),
              array( 'id'=>'96', 'sortname' => 'HM', 'name' =>'Heard and McDonald Islands'),
              array( 'id'=>'97', 'sortname' => 'HN', 'name' =>'Honduras'),
              array( 'id'=>'98', 'sortname' => 'HK', 'name' =>'Hong Kong S.A.R.'),
              array( 'id'=>'99', 'sortname' => 'HU', 'name' =>'Hungary'),
              array( 'id'=>'100', 'sortname' => 'IS', 'name' =>'Iceland'),
              array( 'id'=>'101', 'sortname' => 'IN', 'name' =>'India'),
              array( 'id'=>'102', 'sortname' => 'ID', 'name' =>'Indonesia'),
              array( 'id'=>'103', 'sortname' => 'IR', 'name' =>'Iran'),
              array( 'id'=>'104', 'sortname' => 'IQ', 'name' =>'Iraq'),
              array( 'id'=>'105', 'sortname' => 'IE', 'name' =>'Ireland'),
              array( 'id'=>'106', 'sortname' => 'IL', 'name' =>'Israel'),
              array( 'id'=>'107', 'sortname' => 'IT', 'name' =>'Italy'),
              array( 'id'=>'108', 'sortname' => 'JM', 'name' =>'Jamaica'),
              array( 'id'=>'109', 'sortname' => 'JP', 'name' =>'Japan'),
              array( 'id'=>'110', 'sortname' => 'XJ', 'name' =>'Jersey'),
              array( 'id'=>'111', 'sortname' => 'JO', 'name' =>'Jordan'),
              array( 'id'=>'112', 'sortname' => 'KZ', 'name' =>'Kazakhstan'),
              array( 'id'=>'113', 'sortname' => 'KE', 'name' =>'Kenya'),
              array( 'id'=>'114', 'sortname' => 'KI', 'name' =>'Kiribati'),
              array( 'id'=>'115', 'sortname' => 'KP', 'name' =>'Korea North'),
              array( 'id'=>'116', 'sortname' => 'KR', 'name' =>'Korea South'),
              array( 'id'=>'117', 'sortname' => 'KW', 'name' =>'Kuwait'),
              array( 'id'=>'118', 'sortname' => 'KG', 'name' =>'Kyrgyzstan'),
              array( 'id'=>'119', 'sortname' => 'LA', 'name' =>'Laos'),
              array( 'id'=>'120', 'sortname' => 'LV', 'name' =>'Latvia'),
              array( 'id'=>'121', 'sortname' => 'LB', 'name' =>'Lebanon'),
              array( 'id'=>'122', 'sortname' => 'LS', 'name' =>'Lesotho'),
              array( 'id'=>'123', 'sortname' => 'LR', 'name' =>'Liberia'),
              array( 'id'=>'124', 'sortname' => 'LY', 'name' =>'Libya'),
              array( 'id'=>'125', 'sortname' => 'LI', 'name' =>'Liechtenstein'),
              array( 'id'=>'126', 'sortname' => 'LT', 'name' =>'Lithuania'),
              array( 'id'=>'127', 'sortname' => 'LU', 'name' =>'Luxembourg'),
              array( 'id'=>'128', 'sortname' => 'MO', 'name' =>'Macau S.A.R.'),
              array( 'id'=>'129', 'sortname' => 'MK', 'name' =>'Macedonia'),
              array( 'id'=>'130', 'sortname' => 'MG', 'name' =>'Madagascar'),
              array( 'id'=>'131', 'sortname' => 'MW', 'name' =>'Malawi'),
              array( 'id'=>'132', 'sortname' => 'MY', 'name' =>'Malaysia'),
              array( 'id'=>'133', 'sortname' => 'MV', 'name' =>'Maldives'),
              array( 'id'=>'134', 'sortname' => 'ML', 'name' =>'Mali'),
              array( 'id'=>'135', 'sortname' => 'MT', 'name' =>'Malta'),
              array( 'id'=>'136', 'sortname' => 'XM', 'name' =>'Man (Isle of)'),
              array( 'id'=>'137', 'sortname' => 'MH', 'name' =>'Marshall Islands'),
              array( 'id'=>'138', 'sortname' => 'MQ', 'name' =>'Martinique'),
              array( 'id'=>'139', 'sortname' => 'MR', 'name' =>'Mauritania'),
              array( 'id'=>'140', 'sortname' => 'MU', 'name' =>'Mauritius'),
              array( 'id'=>'141', 'sortname' => 'YT', 'name' =>'Mayotte'),
              array( 'id'=>'142', 'sortname' => 'MX', 'name' =>'Mexico'),
              array( 'id'=>'143', 'sortname' => 'FM', 'name' =>'Micronesia'),
              array( 'id'=>'144', 'sortname' => 'MD', 'name' =>'Moldova'),
              array( 'id'=>'145', 'sortname' => 'MC', 'name' =>'Monaco'),
              array( 'id'=>'146', 'sortname' => 'MN', 'name' =>'Mongolia'),
              array( 'id'=>'147', 'sortname' => 'MS', 'name' =>'Montserrat'),
              array( 'id'=>'148', 'sortname' => 'MA', 'name' =>'Morocco'),
              array( 'id'=>'149', 'sortname' => 'MZ', 'name' =>'Mozambique'),
              array( 'id'=>'150', 'sortname' => 'MM', 'name' =>'Myanmar'),
              array( 'id'=>'151', 'sortname' => 'NA', 'name' =>'Namibia'),
              array( 'id'=>'152', 'sortname' => 'NR', 'name' =>'Nauru'),
              array( 'id'=>'153', 'sortname' => 'NP', 'name' =>'Nepal'),
              array( 'id'=>'154', 'sortname' => 'AN', 'name' =>'Netherlands Antilles'),
              array( 'id'=>'155', 'sortname' => 'NL', 'name' =>'Netherlands The'),
              array( 'id'=>'156', 'sortname' => 'NC', 'name' =>'New Caledonia'),
              array( 'id'=>'157', 'sortname' => 'NZ', 'name' =>'New Zealand'),
              array( 'id'=>'158', 'sortname' => 'NI', 'name' =>'Nicaragua'),
              array( 'id'=>'159', 'sortname' => 'NE', 'name' =>'Niger'),
              array( 'id'=>'160', 'sortname' => 'NG', 'name' =>'Nigeria'),
              array( 'id'=>'161', 'sortname' => 'NU', 'name' =>'Niue'),
              array( 'id'=>'162', 'sortname' => 'NF', 'name' =>'Norfolk Island'),
              array( 'id'=>'163', 'sortname' => 'MP', 'name' =>'Northern Mariana Islands'),
              array( 'id'=>'164', 'sortname' => 'NO', 'name' =>'Norway'),
              array( 'id'=>'165', 'sortname' => 'OM', 'name' =>'Oman'),
              array( 'id'=>'166', 'sortname' => 'PK', 'name' =>'Pakistan'),
              array( 'id'=>'167', 'sortname' => 'PW', 'name' =>'Palau'),
              array( 'id'=>'168', 'sortname' => 'PS', 'name' =>'Palestinian Territory Occupied'),
              array( 'id'=>'169', 'sortname' => 'PA', 'name' =>'Panama'),
              array( 'id'=>'170', 'sortname' => 'PG', 'name' =>'Papua new Guinea'),
              array( 'id'=>'171', 'sortname' => 'PY', 'name' =>'Paraguay'),
              array( 'id'=>'172', 'sortname' => 'PE', 'name' =>'Peru'),
              array( 'id'=>'173', 'sortname' => 'PH', 'name' =>'Philippines'),
              array( 'id'=>'174', 'sortname' => 'PN', 'name' =>'Pitcairn Island'),
              array( 'id'=>'175', 'sortname' => 'PL', 'name' =>'Poland'),
              array( 'id'=>'176', 'sortname' => 'PT', 'name' =>'Portugal'),
              array( 'id'=>'177', 'sortname' => 'PR', 'name' =>'Puerto Rico'),
              array( 'id'=>'178', 'sortname' => 'QA', 'name' =>'Qatar'),
              array( 'id'=>'179', 'sortname' => 'RE', 'name' =>'Reunion'),
              array( 'id'=>'180', 'sortname' => 'RO', 'name' =>'Romania'),
              array( 'id'=>'181', 'sortname' => 'RU', 'name' =>'Russia'),
              array( 'id'=>'182', 'sortname' => 'RW', 'name' =>'Rwanda'),
              array( 'id'=>'183', 'sortname' => 'SH', 'name' =>'Saint Helena'),
              array( 'id'=>'184', 'sortname' => 'KN', 'name' =>'Saint Kitts And Nevis'),
              array( 'id'=>'185', 'sortname' => 'LC', 'name' =>'Saint Lucia'),
              array( 'id'=>'186', 'sortname' => 'PM', 'name' =>'Saint Pierre and Miquelon'),
              array( 'id'=>'187', 'sortname' => 'VC', 'name' =>'Saint Vincent And The Grenadines'),
              array( 'id'=>'188', 'sortname' => 'WS', 'name' =>'Samoa'),
              array( 'id'=>'189', 'sortname' => 'SM', 'name' =>'San Marino'),
              array( 'id'=>'190', 'sortname' => 'ST', 'name' =>'Sao Tome and Principe'),
              array( 'id'=>'191', 'sortname' => 'SA', 'name' =>'Saudi Arabia'),
              array( 'id'=>'192', 'sortname' => 'SN', 'name' =>'Senegal'),
              array( 'id'=>'193', 'sortname' => 'RS', 'name' =>'Serbia'),
              array( 'id'=>'194', 'sortname' => 'SC', 'name' =>'Seychelles'),
              array( 'id'=>'195', 'sortname' => 'SL', 'name' =>'Sierra Leone'),
              array( 'id'=>'196', 'sortname' => 'SG', 'name' =>'Singapore'),
              array( 'id'=>'197', 'sortname' => 'SK', 'name' =>'Slovakia'),
              array( 'id'=>'198', 'sortname' => 'SI', 'name' =>'Slovenia'),
              array( 'id'=>'199', 'sortname' => 'XG', 'name' =>'Smaller Territories of the UK'),
              array( 'id'=>'200', 'sortname' => 'SB', 'name' =>'Solomon Islands'),
              array( 'id'=>'201', 'sortname' => 'SO', 'name' =>'Somalia'),
              array( 'id'=>'202', 'sortname' => 'ZA', 'name' =>'South Africa'),
              array( 'id'=>'203', 'sortname' => 'GS', 'name' =>'South Georgia'),
              array( 'id'=>'204', 'sortname' => 'SS', 'name' =>'South Sudan'),
              array( 'id'=>'205', 'sortname' => 'ES', 'name' =>'Spain'),
              array( 'id'=>'206', 'sortname' => 'LK', 'name' =>'Sri Lanka'),
              array( 'id'=>'207', 'sortname' => 'SD', 'name' =>'Sudan'),
              array( 'id'=>'208', 'sortname' => 'SR', 'name' =>'Suriname'),
              array( 'id'=>'209', 'sortname' => 'SJ', 'name' =>'Svalbard And Jan Mayen Islands'),
              array( 'id'=>'210', 'sortname' => 'SZ', 'name' =>'Swaziland'),
              array( 'id'=>'211', 'sortname' => 'SE', 'name' =>'Sweden'),
              array( 'id'=>'212', 'sortname' => 'CH', 'name' =>'Switzerland'),
              array( 'id'=>'213', 'sortname' => 'SY', 'name' =>'Syria'),
              array( 'id'=>'214', 'sortname' => 'TW', 'name' =>'Taiwan'),
              array( 'id'=>'215', 'sortname' => 'TJ', 'name' =>'Tajikistan'),
              array( 'id'=>'216', 'sortname' => 'TZ', 'name' =>'Tanzania'),
              array( 'id'=>'217', 'sortname' => 'TH', 'name' =>'Thailand'),
              array( 'id'=>'218', 'sortname' => 'TG', 'name' =>'Togo'),
              array( 'id'=>'219', 'sortname' => 'TK', 'name' =>'Tokelau'),
              array( 'id'=>'220', 'sortname' => 'TO', 'name' =>'Tonga'),
              array( 'id'=>'221', 'sortname' => 'TT', 'name' =>'Trinidad And Tobago'),
              array( 'id'=>'222', 'sortname' => 'TN', 'name' =>'Tunisia'),
              array( 'id'=>'223', 'sortname' => 'TR', 'name' =>'Turkey'),
              array( 'id'=>'224', 'sortname' => 'TM', 'name' =>'Turkmenistan'),
              array( 'id'=>'225', 'sortname' => 'TC', 'name' =>'Turks And Caicos Islands'),
              array( 'id'=>'226', 'sortname' => 'TV', 'name' =>'Tuvalu'),
              array( 'id'=>'227', 'sortname' => 'UG', 'name' =>'Uganda'),
              array( 'id'=>'228', 'sortname' => 'UA', 'name' =>'Ukraine'),
              array( 'id'=>'229', 'sortname' => 'AE', 'name' =>'United Arab Emirates'),
              array( 'id'=>'230', 'sortname' => 'GB', 'name' =>'United Kingdom'),
              array( 'id'=>'231', 'sortname' => 'US', 'name' =>'United States'),
              array( 'id'=>'232', 'sortname' => 'UM', 'name' =>'United States Minor Outlying Islands'),
              array( 'id'=>'233', 'sortname' => 'UY', 'name' =>'Uruguay'),
              array( 'id'=>'234', 'sortname' => 'UZ', 'name' =>'Uzbekistan'),
              array( 'id'=>'235', 'sortname' => 'VU', 'name' =>'Vanuatu'),
              array( 'id'=>'236', 'sortname' => 'VA', 'name' =>'Vatican City State (Holy See)'),
              array( 'id'=>'237', 'sortname' => 'VE', 'name' =>'Venezuela'),
              array( 'id'=>'238', 'sortname' => 'VN', 'name' =>'Vietnam'),
              array( 'id'=>'239', 'sortname' => 'VG', 'name' =>'Virgin Islands (British)'),
              array( 'id'=>'240', 'sortname' => 'VI', 'name' =>'Virgin Islands (US)'),
              array( 'id'=>'241', 'sortname' => 'WF', 'name' =>'Wallis And Futuna Islands'),
              array( 'id'=>'242', 'sortname' => 'EH', 'name' =>'Western Sahara'),
              array( 'id'=>'243', 'sortname' => 'YE', 'name' =>'Yemen'),
              array( 'id'=>'244', 'sortname' => 'YU', 'name' =>'Yugoslavia'),
              array( 'id'=>'245', 'sortname' => 'ZM', 'name' =>'Zambia'),
              array( 'id'=>'246', 'sortname' => 'ZW', 'name' =>'Zimbabwe'),
        );

        DB::table('countries')->insert($value);
    }
}
